# Run when the PR is merged
on:
  pull_request:
    types:
      - closed
    inputs:
      aws_role:
        required: true
      ecr_region:
        required: true
        default: 'us-east-1'

jobs:
  terraform:
    name: "Build Terraform"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ github.event.inputs.ecr_region }}
          role-to-assume: ${{ github.event.inputs.aws_role }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve

      - name: Terraform Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1

      - run: |
          echo The Terraform build has been successfully applied
