# Run when the PR is merged
on:
  pull_request:
    types:
      - closed

jobs:
  terraform:
    name: "Build Terraform"
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo The PR was merged
