# Run when the PR is merged
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    name: "Build Terraform"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
