# Only allow destroy to be triggered manually
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Destroy Terraform"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy --auto-approve

      - name: Terraform Destroy Status
        if: steps.destroy.outcome == 'failure'
        run: exit 1

      - run: |
          echo The Terraform build has been successfully destroyed
